In [37]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [38]:
df = pd.read_csv(f'Messy_Employee_dataset.csv')

In [39]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [40]:
df.shape

(1020, 12)

In [41]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Department_Region',
       'Status', 'Join_Date', 'Salary', 'Email', 'Phone', 'Performance_Score',
       'Remote_Work'],
      dtype='str')

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   str
 5   Status             1020 non-null   str
 6   Join_Date          1020 non-null   str
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   str
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   str
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), str(8)
memory usage: 88.8 KB

In [44]:
df.isna().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [45]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [46]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [47]:
df.isna().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [48]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,30.0,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,30.0,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [49]:
df['Phone'].astype(str).str.startswith('-').sum()

np.int64(1020)

In [50]:
df['Phone'] = df['Phone'].astype(str).str.lstrip('-')

In [51]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,1651623197,Average,True
1,EMP1001,Bob,Brown,30.0,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,1898471390,Excellent,True
2,EMP1002,Alice,Jones,30.0,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,1586734256,Poor,False

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                1020 non-null   float64
 4   Department_Region  1020 non-null   str
 5   Status             1020 non-null   str
 6   Join_Date          1020 non-null   str
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   str
 9   Phone              1020 non-null   str
 10  Performance_Score  1020 non-null   str
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), str(9)
memory usage: 88.8 KB

In [53]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'])

In [54]:
df['Status'] = df['Status'].astype('category')
df['Performance_Score'] = df['Performance_Score'].astype('category')

In [55]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True
1,EMP1001,Bob,Brown,30.0,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True
2,EMP1002,Alice,Jones,30.0,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                1020 non-null   float64
 4   Department_Region  1020 non-null   str
 5   Status             1020 non-null   category
 6   Join_Date          1020 non-null   datetime64[us]
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   str
 9   Phone              1020 non-null   str
 10  Performance_Score  1020 non-null   category
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), category(2), datetime64[us](1), float64(2), str(6)
memory usage: 74.9 KB

In [57]:
df[['Department', 'Region']] = df['Department_Region'].str.split('-', expand=True)

In [58]:
df['Region'] = df['Region'].astype('category')
df['Department'] = df['Department'].astype('category')

In [59]:
df.drop('Department_Region', axis=1, inplace=True)

In [60]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30.0,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30.0,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida

In [61]:
df['Age'] = df['Age'].astype(int)

In [62]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                1020 non-null   int64
 4   Status             1020 non-null   category
 5   Join_Date          1020 non-null   datetime64[us]
 6   Salary             1020 non-null   float64
 7   Email              1020 non-null   str
 8   Phone              1020 non-null   str
 9   Performance_Score  1020 non-null   category
 10  Remote_Work        1020 non-null   bool
 11  Department         1020 non-null   category
 12  Region             1020 non-null   category
dtypes: bool(1), category(4), datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 69.0 KB

In [64]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida

In [65]:
from pandas.api.types import CategoricalDtype

order = CategoricalDtype(['Poor', 'Average', 'Good', 'Excellent'], ordered=True)

df['Performance_Score'] = df['Performance_Score'].astype(str).astype(order)

In [66]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida

In [67]:
df['Performance_Score'].dtype

CategoricalDtype(categories=['Poor', 'Average', 'Good', 'Excellent'], ordered=True, categories_dtype=str)

In [69]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                1020 non-null   int64
 4   Status             1020 non-null   category
 5   Join_Date          1020 non-null   datetime64[us]
 6   Salary             1020 non-null   float64
 7   Email              1020 non-null   str
 8   Phone              1020 non-null   str
 9   Performance_Score  1020 non-null   category
 10  Remote_Work        1020 non-null   bool
 11  Department         1020 non-null   category
 12  Region             1020 non-null   category
dtypes: bool(1), category(4), datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 69.2 KB

In [70]:
df['Age'].describe()

count    1020.000000
mean       31.970588
std         5.136901
min        25.000000
25%        30.000000
50%        30.000000
75%        35.000000
max        40.000000
Name: Age, dtype: float64

In [71]:
df['Email'].nunique()

64

In [72]:
df['Email'].value_counts().head(10)

Email
grace.brown@example.com      27
frank.smith@example.com      25
grace.smith@example.com      23
charlie.jones@example.com    22
frank.brown@example.com      22
eva.davis@example.com        21
david.johnson@example.com    21
eva.miller@example.com       21
eva.jones@example.com        21
bob.jones@example.com        20
Name: count, dtype: int64

In [74]:
df.groupby('Department')['Salary'].mean()

Department
Admin         85202.644096
Cloud Tech    84944.434658
DevOps        86003.638624
Finance       82279.519353
HR            85475.379474
Sales         86873.948258
Name: Salary, dtype: float64

In [75]:
df.to_csv('cleaned_Employee_dataset.csv', index=False)

In [76]:
df_check = pd.read_csv('cleaned_Employee_dataset.csv')
df_check.head()

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida